### ISSUE TITLE
Entry cache does not appear to be fully cleared when parent collection deleted

### ISSUE THREAD

**Issue by kjsanger** [cyverse/go-irodsclient#45]
Hi,

I've been using go-irodsclient successfully in https://github.com/wtsi-npg/sqyrrl
After updating to 0.14.15 to take advantage of the new checksum features, I noticed some failures in my tests, not in the application behaviour, but where the test harness adds and removes test data objects from iRODS.

Version: `v0.14.15`

Steps:
1. `fs.MakeDir("/some-path/")`
2. `fs.UploadFile("local-path", "/some-path/some-dir/my-file")`
3. `fs.RemoveDir("/some-path/")`

Later, repeat steps 1-3, but step 2. now fails:

```
<*xerrors.wrapError | 0x14000516e80>: 
      failed to truncate data object /testZone/home/irods/iRODSGetHandler.11244.0553241076/test.txt for overwrite: failed to find the data object for path /testZone/home/irods/iRODSGetHandler.11244.0553241076/test.txt: data object/collection not found for path /testZone/home/irods/iRODSGetHandler.11244.0553241076/test.txt
      {
          msg: "failed to truncate data object /testZone/home/irods/iRODSGetHandler.11244.0553241076/test.txt for overwrite",
          err: <*xerrors.wrapError | 0x14000516780>{
              msg: "failed to find the data object for path /testZone/home/irods/iRODSGetHandler.11244.0553241076/test.txt",
              err: <*types.FileNotFoundError | 0x1400002e200>{
                  Path: "/testZone/home/irods/iRODSGetHandler.11244.0553241076/test.txt",
              },
              frame: {
                  frames: [0x1045e4664, 0x1046ff02c, 0x104748a7c],
              },
          },
          frame: {
              frames: [0x1045e4664, 0x104757844, 0x1048cb5d8],
          },
      }
```

On inspection in the debugger I can see that when the parent directory was deleted, the file entry in the subdirectory was not purged from the cache. Consequently, when a file with the same path is re-added for the next test function, there's an attempt to truncate the "existing" data object (which doesn't actually exist in iRODS) and a file not found error.

Previously I was using v0.14.6, where this didn't happen.

Is there some extra care I need to take in `fs` lifecycle or cache management myself?

Thanks

**Comment by kjsanger** [comment]
(I don't see this with v0.14.14, but do with v0.14.15)

**Comment by iychoi** [comment]
I'll check this out. Thank you!

**Comment by kjsanger** [comment]
I also tested all the release tags between v0.14.6 and v0.14.14 and found no change in the caching behaviour.

**Comment by iychoi** [comment]
Thank you for the testing. I'll check this today. But I didn't change any cache related code but my initial guess is race condition.

**Comment by iychoi** [comment]
@kjsanger Can you check if this test case fails?

https://github.com/cyverse/go-irodsclient/blob/main/test/testcases/fs_cache_test.go#L26

I wasn't able to reproduce the issue on my test environment. But I often see cache inconsistency with other operations. I assume they are mostly caused by iRODS transactions. Each iRODS connection creates a DB transaction and they are not synchronized while the connection is opened. So it is possible that one connection deletes a file/dir and the other connection thinks the file still exists and tries to truncate.

Before the second connection truncates the file, it should request data object information to iRODS server due to cache-miss. Can you check if go-irodsclient really send the request? If it doesn't send the request, there might have a bug in cache code that I cannot easily find.

Thank you!

**Comment by iychoi** [comment]
Before uploading a file, the file will be truncated if it already exists. This way, iRODS will get correct size and hash value. However, if there's transaction/cache issue, the truncation request may fail causing the issue.

I updated the code to try to remove the existing file. This has no harm if the file does not exist.
